/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xiangpi_dynamicblurdemo_activity_StackBlurActivity */

#ifndef _Included_com_hoko_blurlibrary_generator_NativeBlurGenerator
#define _Included_com_hoko_blurlibrary_generator_NativeBlurGenerator
#ifdef __cplusplus
extern "C" {
#endif

#define max(a, b) ((a)>(b)?(a):(b))
#define min(a, b) ((a)<(b)?(a):(b))

JNIEXPORT void JNICALL Java_com_hoko_blurlibrary_generator_NativeBlurGenerator_nativeStackBlur
        (JNIEnv *, jobject, jintArray, jint, jint, jint);

void doInnerBlur(jint *, jint , jint , jint);
#ifdef __cplusplus
}
#endif
#endif
